version: "3"

networks: 
  atelier.net:
    driver: bridge

services:
  api.atelier:
    image: node
    environment:
      - NODE_ENV=dev
      - VHOST_HOSTNAME=api.atelier.local
    ports:
      - "19080:8080"
    volumes:
      - ./atelier_dev:/app/atelier_api
    working_dir: /app/atelier_api
    command: npm run dev
    networks:
      - atelier.net
    links:
      - mysql.atelier:dbcom

  #############################
  # mysql atelier  + adminer
  #############################
  mysql.atelier:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=comroot123
      - MYSQL_USER=atelier_bdd  
      - MYSQL_PASSWORD=atelier_bdd
      - MYSQL_DATABASE=atelier_bdd
    ports:
      - "3307:3306"
    networks:
      - atelier.net
    volumes:
      - ./atelier_api/sql:/var/sql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - atelier.net
    links:
      - mysql.atelier:command