version: "3"

networks: 
  atelier.net:
    driver: bridge

services:
  api.backoffice:
    image: node
    environment:
      - NODE_ENV=dev
      - VHOST_HOSTNAME=api.backoffice.local
    ports:
      - "19080:8080"
    volumes:
      - ./backoffice_dev:/app/backoffice_api
    working_dir: /app/backoffice_api
    command: npm run dev
    networks:
      - atelier.net
    links:
      - mysql.atelier:dbcom

  api.mobile:
    image: node
    environment:
      - NODE_ENV=dev
      - VHOST_HOSTNAME=api.mobile.local
    ports:
      - "19180:8080"
    volumes:
      - ./mobile_dev:/app/mobile_api
    working_dir: /app/mobile_api
    command: npm run dev
    networks:
      - atelier.net
    links:
      - mysql.atelier:dbcom

  api.webapp:
    image: node
    environment:
      - NODE_ENV=dev
      - VHOST_HOSTNAME=api.webapp.local
    ports:
      - "19280:8080"
    volumes:
      - ./webapp_dev:/app/webapp_api
    working_dir: /app/webapp_api
    command: npm run dev
    networks:
      - atelier.net
    links:
      - mysql.atelier:dbcom


  #############################
  # mysql atelier  + phpmyadmin
  #############################
  mysql.atelier:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=comroot123
      - MYSQL_USER=atelier_bdd  
      - MYSQL_PASSWORD=atelier_bdd
      - MYSQL_DATABASE=atelier_bdd
    ports:
      - "3307:3306"
    networks:
      - atelier.net
    volumes:
      - ./atelier_api/sql:/var/sql

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    links:
      - mysql.atelier:db
    networks:
      - atelier.net